import type { PhaseName } from "./types";

type CatalogShot = {
  title: string;
  description: string;
  camera: string;
  movement: string;
  subjectFocus: string;
  emotionBeat: string;
};

export const PHASE_BLUEPRINTS: Record<PhaseName, { title: string; purpose: string; retentionRole: string; shots: CatalogShot[] }> = {
  setup: {
    title: "I. SETUP",
    purpose: "Establish London, Fashion Week context, protagonist arrival and pre-show tension.",
    retentionRole: "Open with scale, city identity, beauty close-ups, countdown and venue anticipation.",
    shots: [
      ["Toàn cảnh London", "Establish London atmosphere and fashion-week journey.", "wide establishing", "slow drone push", "London city", "arrival curiosity"],
      ["Cận Tháp Big Ben", "Iconic Big Ben vertical angle.", "low-angle landmark", "tilt up", "Big Ben", "prestige"],
      ["Cầu Westminster", "River and bridge wide view.", "wide cityscape", "gentle pan", "Westminster Bridge", "place identity"],
      ["Đường phố London", "Tracking through fashion-week street traffic.", "street tracking", "forward tracking", "crowd/city", "urban momentum"],
      ["Biển hiệu LFW", "Close LFW signage.", "insert close-up", "static", "event sign", "event proof"],
      ["Cô gái bước xuống xe", "Main model exits car confidently.", "medium tracking", "follow step-out", "model", "entrance"],
      ["Close-up khuôn mặt", "Face identity close-up, calm confidence.", "beauty close-up", "slow push-in", "face", "identity lock"],
      ["Slow motion tóc bay", "Hair movement in wind.", "medium portrait", "slow motion", "hair", "cinematic beauty"],
      ["Outfit toàn thân", "Full outfit reveal.", "full body", "pedestal tilt", "wardrobe", "fashion reveal"],
      ["Giày cao gót bước đi", "Heel step detail.", "low close-up", "tracking feet", "shoes", "confidence"],
      ["Bước vào venue", "Model enters venue.", "wide interior", "dolly in", "venue entrance", "transition"],
      ["Cổng sự kiện", "Registration / entrance gate.", "wide", "slow push", "check-in area", "scale"],
      ["Thảm đen check-in", "Black carpet and guest/media check-in.", "medium-wide", "tracking", "press zone", "exclusivity"],
      ["Photographer flash", "Photographers fire flashes.", "over-shoulder", "flash cuts", "photographers", "pressure"],
      ["Pose cận mặt", "Model poses before camera.", "close-up", "micro push", "face", "public confidence"],
      ["Background logo", "Step-and-repeat backdrop.", "medium", "static flash", "logo wall", "brand proof"],
      ["Góc nghiêng thần thái", "Side-angle pose.", "profile portrait", "slow orbit", "profile", "fashion attitude"],
      ["Cận mắt long lanh", "Eye macro detail.", "macro close-up", "static", "eyes", "attention lock"],
      ["Nhìn vào ống kính", "Direct gaze into lens.", "portrait", "slow push", "eyes/face", "viewer lock"],
      ["Timelapse chuẩn bị venue", "Venue preparation timelapse.", "wide overhead", "timelapse", "venue", "anticipation"],
      ["Đèn sân khấu setup", "Runway lighting setup.", "wide stage", "light sweep", "lights", "technical scale"],
      ["Sàn runway ban ngày", "Empty runway before show.", "high wide", "slow slide", "runway", "prelude"],
      ["Ghế khách mời", "Chairs and place cards.", "insert", "pan detail", "guest seats", "event detail"],
      ["Backstage entrance", "Backstage corridor entrance.", "wide doorway", "dolly in", "backstage sign", "threshold"],
      ["Đồng hồ đếm ngược", "Countdown clock.", "macro", "static", "clock", "tension"]
    ].map(toShot)
  },
  backstage: {
    title: "II. BACKSTAGE",
    purpose: "Build preparation, beauty, styling, teamwork and emotional tension before runway.",
    retentionRole: "Alternate action, details, face close-ups and emotional preparation to sustain anticipation.",
    shots: [
      ["Cô gái vào backstage", "Model enters narrow backstage corridor.", "medium follow", "handheld follow", "model", "nervous focus"],
      ["Rack đồ", "Wardrobe racks and accessories.", "wide detail", "slow lateral", "wardrobe", "preparation"],
      ["Chọn outfit", "Stylist picks final look.", "medium", "cutaway", "stylist/model", "decision"],
      ["Close-up chất liệu", "Texture, tag and fabric close-up.", "macro", "static", "fabric", "luxury detail"],
      ["Stylist chỉnh trang", "Stylist adjusts outfit.", "medium close-up", "small push", "wardrobe", "craft"],
      ["Makeup bắt đầu", "Foundation preparation.", "close-up", "steady", "makeup", "transformation"],
      ["Cận gương makeup", "Mirror and makeup concentration.", "mirror close", "slow push", "face mirror", "focus"],
      ["Son môi", "Lipstick finishing detail.", "macro", "slow push", "lips", "beauty detail"],
      ["Kẻ eyeliner", "Precise eyeliner close-up.", "macro eye", "static", "eye", "precision"],
      ["Gắn mi giả", "False lash close-up.", "macro", "static", "lashes", "polish"],
      ["Làm tóc", "Hair styling.", "medium", "soft orbit", "hair", "beauty craft"],
      ["Xịt giữ nếp", "Hair spray hold.", "close", "mist motion", "hair mist", "finalization"],
      ["Stylist ủi/steam", "Steam removes wrinkles.", "insert", "steam drift", "garment", "texture"],
      ["Stylist chọn phụ kiện", "Accessories table.", "insert", "pan detail", "jewelry", "selection"],
      ["Thử outfit", "Full look test.", "medium-wide", "tilt", "model outfit", "try-on"],
      ["Mirror full body", "Model checks full look.", "mirror wide", "slow push", "full body", "self-check"],
      ["Thay phụ kiện", "Accessory adjustment.", "close-up", "small pan", "hands/accessory", "refinement"],
      ["Dặm lại makeup", "Final powder and foundation.", "close-up", "static", "face", "durability"],
      ["Tạo kiểu hoàn thiện", "Hair final spray.", "medium close", "slow slide", "stylist/model", "ready"],
      ["Kiểm tra outfit", "Last outfit check.", "medium", "static", "outfit", "confidence"],
      ["Relax phút chốc", "Model rests briefly.", "portrait", "slow push", "face", "calm before storm"],
      ["Uống nước", "Hydration moment.", "close-up", "static", "bottle/cup", "humanity"],
      ["Hít thở sâu", "Deep breath before show.", "close-up", "slow in", "chest/face", "tension"],
      ["Tay nắm tay ủi", "Supportive hand squeeze.", "insert", "static", "hands", "support"],
      ["Nhìn đồng hồ", "Checks time.", "insert/portrait", "cut", "watch/face", "urgency"],
      ["MC thông báo", "MC announces schedule.", "medium", "static", "MC", "cue"],
      ["Đồng đội", "Team hands together.", "overhead", "quick push", "team hands", "team energy"],
      ["Team huddle", "Group huddle before show.", "wide", "circle movement", "team", "unity"],
      ["Đi ra sân khấu", "Lineup moves out.", "tracking", "follow", "models", "transition"],
      ["Cận chân bước đi", "Heels moving backstage.", "low close", "tracking", "feet", "departure"],
      ["Hành lang backstage", "Narrow warm backstage hall.", "wide", "dolly", "corridor", "anticipation"],
      ["Ánh sáng sân khấu hắt vào", "Stage light spills in.", "wide", "light flare", "entrance", "threshold"],
      ["Gương mặt quyết tâm", "Determined close-up.", "close-up", "slow push", "face", "resolve"],
      ["Nhạc dạo nổi lên", "Music cue before runway.", "profile", "sound-led cut", "face", "focus"],
      ["Đứng chờ đến lượt", "Wait for cue.", "medium", "static tension", "model", "heartbeat"]
    ].map(toShot)
  },
  runway: {
    title: "III. RUNWAY",
    purpose: "Deliver fashion show climax: entrance, catwalk, details, audience, finale.",
    retentionRole: "Use runway rhythm: wide scale, close beauty, wardrobe details, crowd reaction, finale payoff.",
    shots: [
      ["Cánh gà sẵn sàng", "Model waits at wing.", "medium", "static tension", "model", "ready"],
      ["Đèn spotlight bật", "Spotlight switches on.", "wide stage", "light ignition", "runway", "activation"],
      ["Bước đầu tiên", "First step onto runway.", "full body", "tracking follow", "model", "show begins"],
      ["Góc toàn thân", "Whole outfit on runway.", "full runway", "dolly backward", "outfit", "reveal"],
      ["Góc nghiêng trái", "Left side angle.", "side medium", "tracking", "silhouette", "shape"],
      ["Góc nghiêng phải", "Right side angle.", "side medium", "tracking", "silhouette", "movement"],
      ["Catwalk chính diện", "Front catwalk hero.", "frontal telephoto", "backward track", "model", "confidence"],
      ["Cận mặt", "Runway face close-up.", "close-up", "slow push", "face", "intensity"],
      ["Thần thái tự tin", "Confident walk.", "medium", "smooth follow", "model", "power"],
      ["Quay chậm 120fps", "Slow motion catwalk.", "medium-wide", "120fps slow", "model", "premium"],
      ["Váy xoay nhẹ", "Dress swirl detail.", "medium", "slow motion", "dress", "flow"],
      ["Chi tiết phụ kiện", "Bag/shoes/accessory close-up.", "macro", "static", "accessory", "luxury detail"],
      ["Cận tay", "Hands and bracelet detail.", "close-up", "tracking detail", "hands", "elegance"],
      ["Cận eo", "Waist cut and fabric.", "medium close", "slow pan", "waist/outfit", "design"],
      ["Cận lưng", "Back silhouette.", "back medium", "follow", "backline", "sensual elegance"],
      ["Bước catwalk", "Runway pace continuation.", "full body", "tracking", "feet/body", "rhythm"],
      ["Publikum reaction", "Audience follows model.", "audience close", "pan", "audience", "social proof"],
      ["Máy ảnh lia", "Cameras follow model.", "insert", "pan whip", "press cameras", "attention"],
      ["Close-up mắt", "Eye contact with lens.", "eye close", "slow push", "eyes", "magnetism"],
      ["Bước qua điểm giữa", "Mid-runway climax.", "wide center", "tracking", "model center", "peak"],
      ["Tương tác ánh nhìn", "Model scans audience.", "medium close", "head turn", "eyes", "connection"],
      ["Quay người", "Turn at runway midpoint.", "full body", "orbit/turn", "model", "pivot"],
      ["Váy bay", "Fabric moves during turn.", "medium", "slow motion", "dress fabric", "motion beauty"],
      ["Bước về cuối", "Move to runway end.", "long lens", "tracking", "model", "approach"],
      ["Dừng pose", "Final outfit pose.", "full body", "static hero", "pose", "iconic"],
      ["Tạo dáng tay", "Professional hand pose.", "medium", "slow push", "hands/pose", "fashion skill"],
      ["Nghiêng đầu", "Soft confident head tilt.", "close-up", "small push", "face", "feminine attitude"],
      ["Cười nhẹ", "Subtle smile toward audience.", "close-up", "slow push", "smile", "warmth"],
      ["Quay chậm", "Slow motion final pose.", "medium", "slow motion", "model", "impact"],
      ["Nhóm mẫu xuất hiện", "Other models join.", "wide", "dolly out", "group", "scale"],
      ["Đi cùng dàn mẫu", "Lineup forms.", "wide runway", "tracking", "models", "formation"],
      ["Kết show cuối đầu", "Model bows.", "medium-wide", "tilt", "model", "gratitude"],
      ["Vỗ tay khán giả", "Audience applause.", "wide audience", "pan", "audience", "payoff"],
      ["Designer xuất hiện", "Designer greets audience.", "medium", "follow", "designer", "recognition"],
      ["Bắt tay designer", "Model and designer handshake.", "medium", "static", "model/designer", "achievement"],
      ["Nhóm cuối sân khấu", "Final lineup.", "wide", "slow push", "group", "finale"],
      ["Chụp ảnh cuối", "Final photo moment.", "wide", "camera flashes", "group", "memory"],
      ["Đi ra cánh gà", "Model exits runway.", "tracking back", "follow", "model", "release"],
      ["Thở phào", "Backstage exhale after show.", "close-up", "slow push", "face", "relief"],
      ["Thay outfit nhanh", "Quick outfit change.", "backstage medium", "fast cuts", "outfit", "pace"],
      ["Outfit 2 xuất hiện", "Second look appears.", "full body", "reveal tilt", "outfit 2", "renewal"],
      ["Bước lần 2", "Second catwalk entrance.", "wide", "tracking", "model", "continuation"],
      ["Góc tele", "Compressed runway telephoto.", "telephoto", "slow push", "model", "glamour"],
      ["Cận chi tiết", "Second outfit detail.", "macro", "static", "fabric/detail", "craft"],
      ["Quay 360 độ", "360 spin at center.", "full body", "orbit 360", "model", "spectacle"],
      ["Walk mạnh mẽ", "Power walk finale.", "frontal", "tracking backward", "model", "authority"],
      ["Ánh sáng đổi màu", "Runway lighting changes.", "wide", "light sweep", "runway", "new mood"],
      ["Khán giả vỗ tay", "Sustained applause.", "audience", "pan", "crowd", "approval"],
      ["Điểm nhấn ánh sáng", "Spotlight isolates model.", "wide", "spotlight follow", "model", "hero moment"],
      ["Look back", "Model looks back.", "back/profile", "slow turn", "face", "connection"],
      ["Bước chéo sân", "Diagonal runway step.", "wide", "diagonal tracking", "model", "geometry"],
      ["Cận môi", "Lip close-up.", "macro close", "static", "lips", "beauty detail"],
      ["Cận tóc", "Hair movement close-up.", "close", "slow motion", "hair", "softness"],
      ["Trang phục chuyển động", "Fabric follows body motion.", "medium", "tracking", "garment", "movement"],
      ["Bước kết", "Final catwalk step.", "full body", "tracking", "model", "completion"],
      ["Tạo dáng cuối", "Final iconic pose.", "full body", "static", "pose", "memory"],
      ["Quay chậm cuối", "Slow applause shot.", "wide/portrait", "slow motion", "model/audience", "emotion"],
      ["Cánh gà chờ", "Model waits to exit.", "backstage", "static", "model", "closure"],
      ["Nhóm cúi chào", "All models bow.", "wide", "dolly out", "group", "final payoff"],
      ["Chụp ảnh tập thể", "Team photo.", "wide", "flash", "group", "documentation"],
      ["Quay flycam", "Runway aerial.", "flycam", "overhead pass", "venue", "scale"],
      ["Toàn cảnh khán giả", "Audience and runway wide.", "wide", "slow pan", "audience", "scale"],
      ["Pháo giấy", "Confetti celebration.", "wide", "falling confetti", "stage", "celebration"],
      ["Ánh sáng tắt dần", "Lights fade.", "wide", "fade out", "stage", "ending"],
      ["Backstage trở lại", "Model returns backstage.", "tracking", "follow", "model", "return"],
      ["Cởi phụ kiện", "Accessories removed.", "insert", "static", "hands/jewelry", "relief"],
      ["Tháo giày", "Tired feet rest.", "close-up", "static", "shoes/feet", "human detail"],
      ["Uống nước", "Hydration after show.", "close-up", "static", "cup", "recovery"],
      ["Uống nước", "Model rests quietly.", "portrait", "slow push", "face", "calm"],
      ["Thở sâu", "Deep breath for next session.", "close-up", "slow push", "face", "reset"]
    ].map(toShot)
  },
  after_party: {
    title: "IV. AFTER PARTY",
    purpose: "Show social proof, celebration, networking, press and final night closure.",
    retentionRole: "Shift into neon party energy, social connection, interviews and calm ending.",
    shots: [
      ["Bước vào after party", "Luxury venue arrival.", "wide entrance", "tracking", "venue", "new chapter"],
      ["Đèn neon", "Neon party lights.", "wide", "light sweep", "club", "energy"],
      ["DJ booth", "DJ starts set.", "insert/wide", "push", "DJ", "party ignition"],
      ["Cầm ly champagne", "Model holds champagne.", "close-up", "static", "glass/hand", "celebration"],
      ["Toast cùng bạn", "Cheers with friend.", "medium", "small push", "friends", "connection"],
      ["Dancer xuất hiện", "Dancer performs.", "wide", "dynamic pan", "dancer", "energy"],
      ["Nhảy theo nhạc", "Model dances lightly.", "medium", "handheld", "model", "release"],
      ["Close-up nhan sắc", "Neon beauty close-up.", "close", "slow push", "face", "glow"],
      ["Chụp hình Polaroid", "Instant photo moment.", "insert", "static", "polaroid", "memory"],
      ["Cười tươi", "Bright smile.", "portrait", "slow push", "smile", "joy"],
      ["Trò chuyện với khách", "Networking.", "medium", "over-shoulder", "guests", "social proof"],
      ["Gặp designer", "Meets designer.", "medium", "static", "designer/model", "status"],
      ["Ôm cảm ơn", "Hugs team.", "medium", "slow push", "team", "gratitude"],
      ["Phỏng vấn nhanh", "Short press interview.", "medium", "static", "press/model", "authority"],
      ["Cần micro", "Microphone close-up.", "close-up", "static", "mic/face", "message"],
      ["Flash liên tục", "Press flashes.", "wide", "flash bursts", "press", "fame"],
      ["Check-in wall", "Backdrop pose.", "medium", "static", "model/backdrop", "public image"],
      ["Viết lên bảng", "Writes on wall.", "medium", "tracking hand", "handwriting", "legacy"],
      ["Ký tên", "Signature close-up.", "insert", "static", "marker", "memory"],
      ["Quay video story", "Phone records story.", "insert", "screen capture", "phone", "social media"],
      ["Đăng story Instagram", "Story upload POV.", "insert", "static", "phone", "distribution"],
      ["Team chụp nhóm", "Group photo with team.", "wide", "flash", "team", "belonging"],
      ["Cam cận mặt", "Purple neon face close-up.", "close", "slow push", "face", "night glamour"],
      ["Moment chill", "Quiet rest.", "medium", "static", "model", "pause"],
      ["Ngắm London đêm", "Rooftop London night.", "wide", "slow pan", "skyline", "reflection"],
      ["Taxi về khách sạn", "Cab ride home.", "medium", "city tracking", "taxi/model", "closure"],
      ["Về đến khách sạn", "Hotel arrival.", "wide", "dolly", "hotel", "ending"],
      ["Tháo trang sức", "Removes jewelry.", "close-up", "static", "earring/hand", "release"],
      ["Tẩy trang", "Removes makeup.", "close", "slow push", "face", "return to self"],
      ["Ngủ ngon", "Rest before next day.", "soft wide", "fade", "bed", "peace"]
    ].map(toShot)
  }
};

function toShot(row: string[]): CatalogShot {
  return {
    title: row[0],
    description: row[1],
    camera: row[2],
    movement: row[3],
    subjectFocus: row[4],
    emotionBeat: row[5]
  };
}
