
from __future__ import annotations

from .schemas import ProductionStep


def base_closed_loop_steps() -> list[ProductionStep]:
    return [
        ProductionStep(
            step_id="input",
            name="Input Poster / Campaign Brief",
            domain="poster-to-storyboard",
            order=1,
            input_keys=["poster_image_url|poster_image_path", "campaign_brief"],
            output_keys=["normalized_input"],
            hard_rules=["NO_INPUT_IMAGE_OR_BRIEF -> BLOCK"],
        ),
        ProductionStep(
            step_id="storyboard",
            name="Storyboard Engine",
            domain="storyboard-engine",
            order=2,
            input_keys=["normalized_input"],
            output_keys=["storyboard", "scene_plan", "camera_plan"],
            hard_rules=["NO_STORYBOARD -> NO_RENDER_PACKAGE"],
        ),
        ProductionStep(
            step_id="multi_angle",
            name="Single Image Multi-Angle Planner",
            domain="multi-angle-storyboard",
            order=3,
            required=False,
            input_keys=["poster_image_url|poster_image_path", "storyboard"],
            output_keys=["angle_scenes", "multi_angle_payloads"],
            hard_rules=["NO_SOURCE_IMAGE -> SKIP_MULTI_ANGLE"],
        ),
        ProductionStep(
            step_id="higgsfield_seedance2",
            name="Higgsfield × Seedance2 Optimizer",
            domain="higgsfield-seedance2",
            order=4,
            required=False,
            input_keys=["storyboard", "angle_scenes"],
            output_keys=["seedance_optimized_prompts"],
            hard_rules=["NO_CAMERA_GRAMMAR -> SKIP_OPTIMIZER"],
        ),
        ProductionStep(
            step_id="provider_payload",
            name="Provider Payload Compiler",
            domain="multi-provider",
            order=5,
            input_keys=["storyboard", "seedance_optimized_prompts"],
            output_keys=["provider_payloads"],
            hard_rules=["NO_PROVIDER_PAYLOAD -> NO_PROVIDER_RENDER"],
        ),
        ProductionStep(
            step_id="provider_render",
            name="Provider Render Dispatch",
            domain="multi-provider",
            order=6,
            input_keys=["provider_payloads"],
            output_keys=["scene_video_artifacts"],
            hard_rules=["NO_SCENE_VIDEO_ARTIFACTS -> BLOCK_FINAL_ASSEMBLY"],
        ),
        ProductionStep(
            step_id="html_render_fallback",
            name="HTML Motion Render Fallback",
            domain="html-render",
            order=7,
            required=False,
            input_keys=["storyboard"],
            output_keys=["html_scene_artifacts"],
            hard_rules=["USE_WHEN_PROVIDER_DISABLED_OR_FAILED"],
        ),
        ProductionStep(
            step_id="drama",
            name="Drama Engine",
            domain="drama-engine",
            order=8,
            required=False,
            input_keys=["storyboard"],
            output_keys=["drama_enhanced_scene_plan"],
            hard_rules=["WEAK_HOOK -> REWRITE_BEFORE_RENDER"],
        ),
        ProductionStep(
            step_id="avatar",
            name="Avatar Engine",
            domain="avatar-engine",
            order=9,
            required=False,
            input_keys=["campaign_brief", "storyboard"],
            output_keys=["avatar_plan", "avatar_artifacts"],
            hard_rules=["ONLY_REQUIRED_FOR_PRESENTER_WORKFLOW"],
        ),
        ProductionStep(
            step_id="audio",
            name="Audio Engine",
            domain="audio-engine",
            order=10,
            input_keys=["storyboard", "voiceover_script"],
            output_keys=["voice_artifact", "bgm_artifact", "mixed_audio_artifact"],
            hard_rules=["NO_AUDIO -> NO_FINAL_EXPORT"],
        ),
        ProductionStep(
            step_id="subtitle",
            name="Smart Subtitle Engine",
            domain="smart-subtitle",
            order=11,
            input_keys=["voiceover_script", "mixed_audio_artifact"],
            output_keys=["ass_subtitle", "srt_subtitle", "subtitle_burn_plan"],
            hard_rules=["NO_SUBTITLE_SAFE_ZONE -> NO_BURN_IN"],
        ),
        ProductionStep(
            step_id="assembly",
            name="Production Render Assembly",
            domain="production-render",
            order=12,
            input_keys=["scene_video_artifacts|html_scene_artifacts", "mixed_audio_artifact", "ass_subtitle"],
            output_keys=["final_video_artifact"],
            hard_rules=["NO_FINAL_MP4 -> FAIL_CONTRACT"],
        ),
        ProductionStep(
            step_id="artifact_contract",
            name="Artifact Storage + FinalVideoContract",
            domain="artifact-contracts",
            order=13,
            input_keys=["final_video_artifact"],
            output_keys=["final_video_contract"],
            hard_rules=["NO_CONTRACT -> NO_DOWNLOAD"],
        ),
        ProductionStep(
            step_id="analytics_feedback",
            name="AI Video Factory Analytics Feedback",
            domain="ai-video-factory",
            order=14,
            required=False,
            input_keys=["final_video_contract", "published_video_metrics"],
            output_keys=["winner_patterns", "next_storyboard_mutations"],
            hard_rules=["ONLY_AFTER_PUBLISH"],
        ),
    ]
